{% set name = "immutables" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b55ffaf0449790242feb4c56ab799ea7af92801a0a43f9e2f4f8af2ab24dfc4a
  patches:
    - patches/python_39_types_capitalization.patch  # [py>=39]

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c')}}
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - immutables
  requires:
    - pip
    - pytest >=7.4,<8
    - mypy >=1.4,<2
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://github.com/MagicStack/immutables
  license: Apache-2.0 AND 0BSD
  license_family: Apache
  license_file: LICENSE
  summary: Immutable Collections
  description: A high-performance immutable mapping type for Python.
  dev_url: https://github.com/MagicStack/immutables
  doc_url: https://github.com/MagicStack/immutables

extra:
  recipe-maintainers:
    - nicoddemus
