{% set name = "immutables" %}
{% set version = "0.10" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e661bebe9428942ebdb569b718d8c7895ec939858d307655844e2a7994ad2a9e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True  # [py27]
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - immutables
  commands:
    - pytest tests

about:
  home: https://github.com/MagicStack/immutables
  license: Apache-2.0
  license_family: APACHE
  license_file: 'LICENSE'
  summary: Immutable Collections
  description: "An immutable mapping type for Python."
  dev_url: 'https://github.com/MagicStack/immutables'

extra:
  recipe-maintainers:
    - nicoddemus
