travis:
  secure:
    BINSTAR_TOKEN: qQe0M3oXhaMifuLypV4zTRL0IbujVvqsOJWhYqJR4+ECT15dfVlKPQMBrw1Aw/EALOZL865lm3X1XghjifTj/h5IUJ31YMRtAnHV6WLMICi4Vm2af60SzA1jHkmE8ENKk0KlUXiPmYdppSxoQcG6pGZ7fPW9WkFl+Q9UcR21Pd4Nff1poqUp/ZyWYxUlTA0/WBxGIm3DhxMSF1ec4lG0ANoffcw3pNI2MoLXmJOl2GzPSunafyU/UJSSJY2bCNWnbWZdkLPfDhHod8yawWQ3VMjgyBLufG6yS4MTS3BiLyTvtPe5uqskVJPrfvx0IoCvls04Mkf3XxmlMJvHaflgIQ3dvNpqfUkW+D4Ko7c3ug+OpPt1mm8ZJlxpcO9PXDj+iUIDBwypKwQyioJn1gHRrFe+gjUQ49u377QuqUhGQJvA11+vaByphbNW6AKWpb9wMrVjv5UQAL0zJRyKJvqVBEUtn9DarBfrSO0hOOb1l+Vxe5QYNpjiR5RVeMXNPlxIqoLJ0b23dyHGR9yil1t2x7jorY1yovIhBbR9IRtpGkyFi8J4VSRjfCVbB/UHWakj2S/MBuke+u5HWxG2XjMjUco/VaW3c0gFz1sbGEe9LLLJQyxCICP98C8g+3GYwlg958MEtFBtXqMSsshjGGiApDZ9/LVjaT9cnUkLnUaXt2Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
